### PR TITLE
Provide initial version of currently available docs

### PR DESCRIPTION
**Pull request by i-trofimtschuk**
https://redis-tasks.readthedocs.io/en/feature-allthedocs/

### CODE REVIEW

**Review by bastir85 — APPROVED** [review]
I looked through for formating problems etc. It seems fine except:
https://redis-tasks.readthedocs.io/en/feature-allthedocs/redis_tasks.html#module-redis_tasks.conf
Formating of the `RESPONSE_CALLBACKS` 

Not a merge blocker.

**Review by LutherEngelsnot — APPROVED** [review]
Skimmed, read a bit, used links and checked it out. Looks fine (except the one problem sebastian already found). The only other visual problem I found is probably related to the site, where the docs are shown, not with this PR. What I mean is the highlighting for code links, if the code is longer: https://redis-tasks.readthedocs.io/en/feature-allthedocs/_modules/redis_tasks/conf.html#RTRedis

**Comment by i-trofimtschuk** [comment]
> I looked through for formating problems etc. It seems fine except:
> https://redis-tasks.readthedocs.io/en/feature-allthedocs/redis_tasks.html#module-redis_tasks.conf
> Formating of the `RESPONSE_CALLBACKS`
> 
> Not a merge blocker.

@bastir85 i know, but i think i can't fix this quickly - would need to dig a bit in api-docs stuff, so would leave as is for now

**Comment by i-trofimtschuk** [comment]
> Skimmed, read a bit, used links and checked it out. Looks fine (except the one problem sebastian already found). The only other visual problem I found is probably related to the site, where the docs are shown, not with this PR. What I mean is the highlighting for code links, if the code is longer: https://redis-tasks.readthedocs.io/en/feature-allthedocs/_modules/redis_tasks/conf.html#RTRedis

@LutherEngelsnot yes, i think this is a doc-template issue -  we could change it, but i also don't see this as merge blocker

**Pull request merged**
