### PR TITLE
Change to using native github dependabot

### PR DESCRIPTION
**Pull request by i-trofimtschuk**
also upgrade all dependencies

### CODE REVIEW

**Review by bastir85 — APPROVED** [review]

**Comment by bastir85** [comment]
i think we can merge this, @vasilty could you comment.

**Comment by i-trofimtschuk** [comment]
@dkusnik @LutherEngelsnot what do you think?
@bastir85 there is some implications of native dependabot that we should think about
we cant use protected branches, but maybe other ways of access control will work

**Comment by i-trofimtschuk** [comment]
i cant approve, but LGTM as i suggest this ^^

**Review by LutherEngelsnot — APPROVED** [review]
Looks fine, except on question I am not sure about. Do we need to set a target branch?

**Comment by i-trofimtschuk** [comment]
@dependabot squash and merge

**Pull request merged**
